server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  sql:
    init:
      mode: always # execute sql script on app start
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true # use ip address instead of hostname
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: Cards
    description: Cards Microservice
    version: 1.0.0

logging:
  level:
    com:
      fetrova:
        cards: DEBUG