spring:
  application:
    name: gatewayserver
  config:
    #optional dont fail the app start if config server is not available
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true


info:
  app:
    name: gatewayserver
    description: Gateway Server Application
    version: 1.0.0

logging:
  level:
    com:
      fetrova:
        gatewayserver: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10 # how many last requests should be considered to change the circuit breaker state
        permitted-number-of-calls-in-half-open-state: 2 # minimum number of requests in half-open state
        failure-rate-threshold: 50 # percentage of failed requests that should happen before opening the circuit breaker
        wait-duration-in-open-state: 10000 # duration of the circuit breaker open state, 10 seconds