spring:
  application:
    name: gatewayserver
  config:
    #optional dont fail the app start if config server is not available
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true


info:
  app:
    name: gatewayserver
    description: Gateway Server Application
    version: 1.0.0

logging:
  level:
    com:
      fetrova:
        gatewayserver: DEBUG