#@fullPath = http://localhost:8080/api
@fullPath = http://localhost:8072/fetrovabank/accounts/api
@actuatorPath = http://localhost:8080/actuator

### Get Customer Details
GET {{fullPath}}/fetchCustomerDetails?mobileNumber=0610001122
Content-Type: application/json

