services:
  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      service: network-deploy-services
      file: common-config.yml

  configserver:
    image: "fearaujo/configserver:s6"
    container_name: "configserver"
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 5s
    extends:
      service: microservice-base-config
      file: common-config.yml

  accounts:
    image: "fearaujo/accounts:s6"
    container_name: "accounts"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      service: microservice-configserver-config
      file: common-config.yml
    environment:
      SPRING_APPLICATION_NAME: "accounts"

  loans:
    image: "fearaujo/loans:s6"
    container_name: loans
    ports:
      - "8090:8090"
    networks:
      - araujobank
    extends:
      service: microservice-configserver-config
      file: common-config.yml
    environment:
      SPRING_APPLICATION_NAME: "loans"

  cards:
    image: "fearaujo/cards:s6"
    container_name: "cards"
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      service: microservice-configserver-config
      file: common-config.yml
    environment:
      SPRING_APPLICATION_NAME: "cards"

networks:
  araujobank:
    driver: "bridge"