@fullPath = localhost:8071

### Encrypt data
POST {{fullPath}}/encrypt
Content-Type: application/json

< ./payloads/encrypt.json

### Decrypt data
POST {{fullPath}}/decrypt
Content-Type: application/json

< ./payloads/encrypt.json
