server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  sql:
    init:
      mode: always # execute sql script on app start
  jpa:
    show-sql: true
  config:
    #optional dont fail the app start if config server is not available
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true # use ip address instead of hostname
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: accounts
    description: Accounts Microservice
    version: 1.0.0

logging:
  level:
    com:
      fetrova:
        accounts: DEBUG