spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome - PROD ENV"
  contactDetails:
    name: "Felipe - PROD"
    email: "felipe@test.com"
  onCallSupport:
    - +310610001122
    - +310610001133