@fullPath = localhost:8090/api

### Create card
POST {{fullPath}}/create?mobileNumber=0610001122
Content-Type: application/json


### Fetch card
GET {{fullPath}}/fetch?mobileNumber=0610001122
Content-Type: application/json


### Update card
PUT {{fullPath}}/update
Content-Type: application/json

< ./payloads/updateLoans.json

### Delete card
DELETE {{fullPath}}/delete?mobileNumber=0610001122
Content-Type: application/json

### Get build info
GET {{fullPath}}/build-info
Content-Type: application/json

### Contact info
GET {{fullPath}}/contact-info
Content-Type: application/json

### Refresh actuator endpoints
POST localhost:8090/actuator/refresh
Content-Type: application/json