services:
  network-deploy-services:
    networks:
      - araujobank

  microservice-base-config:
    extends:
      service: network-deploy-services
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
