services:

  # Databases

  accountsdb:
    container_name: "accountsdb"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      service: microservice-db-config
      file: common-config.yml

  loansdb:
    container_name: "loansdb"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      service: microservice-db-config
      file: common-config.yml

  cardsdb:
    container_name: "cardsdb"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      service: microservice-db-config
      file: common-config.yml

  # Services

  configserver:
    image: "fearaujo/configserver:s7"
    container_name: "configserver"
    ports:
      - "8071:8071"
    #    depends_on:
    #      rabbitmq:
    #        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 5s
    extends:
      service: microservice-base-config
      file: common-config.yml

  accounts:
    image: "fearaujo/accounts:s7"
    container_name: "accounts"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    extends:
      service: microservice-configserver-config
      file: common-config.yml
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountsdb

  loans:
    image: "fearaujo/loans:s7"
    container_name: loans
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    networks:
      - araujobank
    extends:
      service: microservice-configserver-config
      file: common-config.yml
    environment:
      SPRING_APPLICATION_NAME: "loans"
      #containers are in the same network that's why we can use the original port
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb

  cards:
    image: "fearaujo/cards:s7"
    container_name: "cards"
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    extends:
      service: microservice-configserver-config
      file: common-config.yml
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/cardsdb

networks:
  araujobank:
    driver: "bridge"